[package]
name = "kontrollanzeige-1"
version = "0.1.0"
authors = ["remolueoend <remolueoend@users.noreply.github.com>"]
edition = "2021"
resolver = "2"

[patch.crates-io]
embedded-io = { path = "./embedded-io" }


[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
esp32 = "=0.15.0"
esp-idf-sys = { version = "=0.31.5", features = ["binstart"] }
esp-idf-svc = { version = "=0.42.1", features = ["experimental", "alloc"] }
esp-idf-hal = "=0.38.0"
embedded-svc = "=0.22"
log = "0.4"
anyhow = "1"
rgb = "0.8"
toml-cfg = "0.1"


[build-dependencies]
embuild = "0.28"
anyhow = "1"
